# Defina a imagem base
FROM node:16

# Defina o diretório de trabalho
WORKDIR /app

# Copie o package.json e o package-lock.json
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante dos arquivos do projeto
COPY . .

# Exponha a porta 3000
EXPOSE 3000

# Defina o comando para iniciar a aplicação
CMD [ "npm", "run", "dev" ]