<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'neko-kirame',
                'is_active' => true,
                'login' => 'neko',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['administrador']),
                'avatar' => null,
                'name' => 'Ellyson Santos',
                'nickname' => 'Neko Kirame',
                'email' => null,
                'age' => null,
                'city' => 'Guarabira',
                'state' => 'Paraíba',
                'country' => 'Brasil',
                'biography' => 'Sou essencialmente um Designer Gráfico, mas também edito vídeos. Minha empreitada pelo mundo dos animes começou com D.Gray-Man, Katekyo Hitman Reborn e Fairy Tail. Daí para frente, as coisas desandaram, e não é à toa que hoje sou um dos administradores desta rede. E não só isso, como também faço todas as artes daqui, gerencio as redes sociais e é isso, acho que só!',
                'social_networks' => null,
                'likes' => null,
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'suzuh',
                'is_active' => true,
                'login' => 'suzuh',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['administrador']),
                'avatar' => null,
                'name' => 'João Gabriel',
                'nickname' => 'Suzuh',
                'email' => null,
                'age' => null,
                'city' => 'Cabo Frio',
                'state' => 'Rio de Janeiro',
                'country' => 'Brasil',
                'biography' => 'Sou um desenvolvedor em desenvolvimento e um amante de animes e doramas. Meu primeiro anime foi Mirai Nikki e desde então estou sempre nesse mundo. Atualmente sou e responsável pelo desenvolvimento e manutenção do site.',
                'social_networks' => null,
                'likes' => null,
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'takashi',
                'is_active' => true,
                'login' => 'takashi',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['administrador']),
                'avatar' => null,
                'name' => 'Antônio Medeiros Lopes',
                'nickname' => 'Takashi',
                'email' => null,
                'age' => null,
                'city' => 'Pelotas',
                'state' => 'Rio Grande do Sul',
                'country' => 'Brasil',
                'biography' => 'Minha jornada no mundo otaku começou há menos tempo do que a maioria das pessoas de hoje, foi pesquisando sobre séries de zumbis que me deparei com High School of the Dead e hoje sou o que sou e não tenho intenções de mudar.',
                'social_networks' => null,
                'likes' => null,
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'nhk',
                'is_active' => true,
                'login' => 'nhk',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['redator']),
                'avatar' => null,
                'name' => 'Eduardo Borges',
                'nickname' => 'NHK',
                'email' => null,
                'age' => null,
                'city' => 'Itaguaí',
                'state' => 'Rio de Janeiro',
                'country' => 'Brasil',
                'biography' => 'Olá Jovem! Como vai? Eu sou o NHK, e posso dizer que hoje sou um grande senpai dos animes. Mas cara, como é bom assistir um animezinho com um suco de laranja geladinho! Ah, de fato, isso é muito bom! Se for assistir, é só me convidar. Vai um café também?.',
                'social_networks' => null,
                'likes' => null,
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'jojo',
                'is_active' => true,
                'login' => 'jojo',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['locutor']),
                'avatar' => null,
                'name' => 'Jordanna Maria',
                'nickname' => 'Jojo',
                'email' => null,
                'age' => null,
                'city' => 'Goiás',
                'state' => 'Goiás',
                'country' => 'Brasil',
                'biography' => 'Apaixonada pela cultura asiática desde sempre! Amo animes (ação, comédia, yuri, yaoi, ecchi, enfim... Se eu curtir, não importa o gênero!), coisas fofinhas, filmes de terror (Amo assassinatos! Sangue, sangue, sangue! XD), enfim, "meus gostos são peculiares, você não me entenderia" kkkk! Sou uma pessoa muito tímida, por incrível que pareça! Gosto de ficar em casa, jogar vídeo game, desenhar, assistir animes e doramas, e ler meus mangás/light novels! ^^.',
                'social_networks' => null,
                'likes' => null,                
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'luh',
                'is_active' => true,
                'login' => 'luh',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['locutor', 'redator']),
                'avatar' => null,
                'name' => 'Luiz Fernando',
                'nickname' => 'Luh',
                'email' => null,
                'age' => null,
                'city' => 'Minas Gerais',
                'state' => 'Minas Gerais',
                'country' => 'Brasil',
                'biography' => '(L)indo por natureza</br>(U)ma fonte de beleza</br>(I)Inteligente, só que não</br>(Z)Zoeiro e sem noção',
                'social_networks' => null,
                'likes' => null,
            ],
            [
                'created_at' => now(),
                'updated_at' => now(),
                'slug' => 'mizaki',
                'is_active' => true,
                'login' => 'mizaki',
                'password' => Hash::make('1234'),
                'access_levels' => json_encode(['locutor', 'redator']),
                'avatar' => null,
                'name' => 'Leonora',
                'nickname' => 'Mizaki',
                'email' => null,
                'age' => null,
                'city' => 'Capoeiras',
                'state' => 'Pernambuco',
                'country' => 'Brasil',
                'biography' => 'Gosto muito de contar histórias (especialmente mitologia e lendas urbanas). Sou do tipo que adora compartilhar meus gostos e saber o que os outros têm a me dizer',
                'social_networks' => null,
                'likes' => null,
            ]
        ]);
    }
}
